name: Action CI Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    defaults:
      run:
        shell: "/usr/bin/arch -arch ${{ env.arch }} /bin/bash {0}"

    steps:
      - uses: actions/checkout@v2

      - name: Run on arm64e
        env:
          ARCH: arm64e
        run: uname -a
        
      - name: Run on x86_64
        env:
          ARCH: x86_64
        run: uname -a
