name: Action CI Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run get uname
        run: uname -a
        
      - name: Run get xcode list
        run: ls -n /Applications/ | grep Xcode
