name: Action CI Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: iOS ${{ matrix.versions.ios-range }} Test
    runs-on: ${{ matrix.versions.os }}
    
    strategy:
      matrix:
        versions:
          - os: macos-10.15
            ios-config: 12.x
            xcode-version: 10.x

          - os: macos-11
            ios-config: 13.x
            xcode-version: 11.x
            
          - os: macos-11
            ios-config: 14.x
            xcode-version: 12.x
            
          - os: macos-11
            ios-config: 15.x
            xcode-version: 13.x

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@881be567d30efed8fb3f12b5099d68c3fb72aa3d
        env:
          xcode-version: ${{ matrix.versions.xcode-version == '' && env.default_xcode-version || matrix.versions.xcode-version }}
        with:
          xcode-version: ${{ env.xcode-version }}

      - name: Run get uname
        run: uname -a

      - name: Run get xcode list
        run: ls -n /Applications/ | grep Xcode
      
      - name: Run get simulation list
        run: xcrun xctrace list devices || instruments -s devices
# 2>&1 | grep \'^iPhone\
